IT-Academy-Social-Projects-KRV/CMIYC

Frontend/angular.json
Frontend/package.json

Added bootstrap5 (Connect template to UI)

---

Frontend/src/app/admin-create-schema-form/admin-create-schema-form.component.html
Frontend/src/app/admin-manage-schema-list/admin-manage-schema-list.component.html
Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.html
Frontend/src/app/admin-user-form/admin-user-form.component.html
Frontend/src/app/app-routing.module.ts
Frontend/src/app/app.component.html
Frontend/src/app/app.module.ts
Frontend/src/app/errorpages/error403/error403.component.css
Frontend/src/app/errorpages/error403/error403.component.html
Frontend/src/app/errorpages/error404/error404.component.css
Frontend/src/app/errorpages/error404/error404.component.html
Frontend/src/app/errorpages/error500/error500.component.css
Frontend/src/app/errorpages/error500/error500.component.html
Frontend/src/app/header/header.component.css
Frontend/src/app/header/header.component.html
Frontend/src/app/login-form/login-form.component.html
Frontend/src/app/login-form/login-form.component.ts
Frontend/src/app/register/register.component.html
Frontend/src/app/register/register.component.ts
Frontend/src/app/search-response/search-response.component.html
Frontend/src/app/sidebar/sidebar.component.css
Frontend/src/app/sidebar/sidebar.component.html
Frontend/src/app/two-factor-authentication-form/two-factor-authentication-form.component.html
Frontend/src/app/two-factor-authentication-form/two-factor-authentication-form.component.ts
Frontend/src/app/user-search-interface/user-search-interface.component.html
Frontend/src/app/user-search-interface/user-search-interface.component.ts
Frontend/src/app/utils/validation.ts
Frontend/src/index.html

Feature 50 user validation for forms malyarskyy

---

Backend/microservices/connector/ResourceServerManual.md

Howto use and configure Resource Server in Microservices:

Feature 73 create resource server igor

---

Backend/microservices/authority/pom.xml
Backend/microservices/authority/src/main/java/com/ms/authority/config/MethodSecurityConfig.java
Backend/microservices/authority/src/main/java/com/ms/authority/config/OAuth2AuthorizationServerConfigJwt.java
Backend/microservices/authority/src/main/java/com/ms/authority/config/ResourceServerConfig.java
Backend/microservices/authority/src/main/java/com/ms/authority/controller/UserController.java
Backend/microservices/authority/src/main/java/com/ms/authority/service/UserService.java

Also deleted some unused dependencies

Added support for multiple scopes and configuration for user registration endpoint

---

Backend/microservices/data/pom.xml
Backend/microservices/data/src/main/java/com/ms/data/config/JWTSecurityConfigData.java
Backend/microservices/data/src/main/java/com/ms/data/controller/DataController.java
Backend/microservices/data/src/main/resources/application.yml

configure OAuth2 Resource Server with Data Api

---

Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.ts
Frontend/src/app/header/header.component.html
Frontend/src/app/header/header.component.ts
Frontend/src/app/login-form/login-form.component.html
Frontend/src/app/login-form/login-form.component.ts
Frontend/src/app/shared/auth.service.ts

Added fixes on login form and header

---

Frontend/src/app/shared/http.client.service.ts

If user search form is sent, data will not be returned from server because content type header wasnt actually set.
This pull request fixes this error.

Bugfix: fixed content type not set bug

---

Backend/external-apis/mock-repository/pom.xml
Backend/external-apis/mock-repository/src/main/java/com/external/mockrepository/MockEndpoint.java
Backend/external-apis/mock-repository/src/main/webapp/WEB-INF/web.xml
Backend/external-apis/mock-repository/src/main/webapp/index.jsp
Backend/external-apis/rest-server/pom.xml
Backend/external-apis/rest-server/src/main/java/com/external/rest/Server.java
Backend/external-apis/rest-server/src/main/webapp/WEB-INF/web.xml
Backend/external-apis/rest-server/src/main/webapp/index.jsp
Backend/external-apis/soap-server/pom.xml
Backend/external-apis/soap-server/src/main/java/com/external/soap/SoapApp.java
Backend/external-apis/soap-server/src/main/resources/application.properties
Backend/external-apis/soap-server/src/main/resources/application.yml
Backend/external-apis/soap-server/src/main/resources/banner.txt
Backend/external-apis/websocket-server/pom.xml
Backend/external-apis/websocket-server/src/main/java/com/external/websocketserver/WebsocketEndpoint.java
Backend/external-apis/websocket-server/src/main/webapp/WEB-INF/beans.xml
Backend/external-apis/websocket-server/src/main/webapp/WEB-INF/web.xml
Backend/external-apis/websocket-server/src/main/webapp/index.jsp

Skeletons for:
External repository(servlet)
REST server(servlet)
SOAP server(Spring)
WebSocket server(javax.websocket)

Skeleton for external services was added

---

Frontend/src/app/admin-user-form/admin-user-form.component.html
Frontend/src/app/admin-user-form/admin-user-form.component.ts
Frontend/src/app/shared/http.client.service.ts

Send new user data from admin to auth

Send new user data from admin to auth

---

Backend/external-apis/rest-server/pom.xml
Backend/external-apis/rest-server/src/main/java/com/external/connection/ConnectDataSource.java
Backend/external-apis/rest-server/src/main/java/com/external/rest/Server.java

Added:
Pom.xml - necessary dependencies;
Server.class - logic;
ConnectDataSource.class - logic that gives an opportunity to connect REST api to mocked data repository

feature_79_REST-API_Horishny

---

Frontend/src/app/shared/http.client.service.ts

Now schema is sent correctly from UI

Fixed content type error

---

Backend/external-apis/README.md
Backend/external-apis/rest-server/pom.xml
Backend/external-apis/rest-server/src/main/java/com/external/connection/ConnectDataSource.java
Backend/external-apis/rest-server/src/main/java/com/external/rest/Server.java

Changed websocket client to use Thread.sleep until the response is received or throw exception if there was no response.
Added handling of GET request on /rest endpoint. Added line to wiki on how to use it.

Refactor rest server and added GET request

---

Backend/microservices/search/pom.xml
Backend/microservices/search/src/main/java/com/ms/search/config/CaffeineConfig.java
Backend/microservices/search/src/main/java/com/ms/search/connectInterface/ConnectorConnect.java
Backend/microservices/search/src/main/java/com/ms/search/connectInterface/DataConnect.java
Backend/microservices/search/src/main/java/com/ms/search/controller/SearchController.java
Backend/microservices/search/src/main/resources/application.yml

Now responses from data and connector api are stored in cache and deleted after 8 hours

Added caching of responses

---

Backend/microservices/data/src/main/java/com/ms/data/controller/DataController.java
Backend/microservices/data/src/main/java/com/ms/data/controller/RestExceptionHandler.java
Backend/microservices/data/src/main/java/com/ms/data/exception/CurrentSelectedSchemaException.java
Backend/microservices/data/src/main/java/com/ms/data/service/CloudStorageService.java

You can test it by deleting schema on schema admin page,also you can not delete current choosed schema(test it please)

added deleting schema opportunity

---

Frontend/src/app/shared/http.client.service.ts

Error massage when user already exist.

Edit user registration on UI

---

Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.html
Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.ts

autohide pagination if nothing to page, 
items per page now 10

feature_291_ChangePageSizeUserAdmin_horishny

---

Backend/custom-starter/README.MD
Backend/external-apis/README.md
Backend/external-apis/mock-repository/src/main/java/com/external/dto/API.java
Backend/external-apis/mock-repository/src/main/java/com/external/dto/SearchRequest.java
Backend/microservices/connector/README.MD
Backend/microservices/connector/src/main/java/com/ms/connector/controller/SearchQueryController.java
Backend/microservices/connector/src/main/java/com/ms/connector/service/ApiService.java
Backend/microservices/connector/src/main/resources/application.yml

api1 -> NCIC
api2 -> FRED
api3 -> DataGOV
**BEFORE TESTING SELECT NEW SCHEMA IN SCHEMA ADMIN PAGE: newSchema.xml**

Update README and rename APIs

---

Backend/microservices/authority/src/main/java/com/ms/authority/service/UserService.java

Now you receive registration message only once(before this we were able to double tap on create button and receive our message twice)

add syncronized to register method

---

Backend/microservices/authority/src/main/java/com/ms/authority/entity/Role.java
Backend/microservices/authority/src/main/java/com/ms/authority/service/UserService.java

fix admin users deleting

---

Backend/external-apis/mock-repository/pom.xml
Backend/external-apis/mock-repository/src/main/java/com/external/dto/SearchResponse.java
Backend/external-apis/mock-repository/src/main/java/com/external/repository/PersonRepository.java
Backend/external-apis/mock-repository/src/test/java/com/external/SearchRequestUnitTests.java
Backend/external-apis/mock-repository/src/test/java/com/external/ServerUnitTests.java
Backend/external-apis/mock-repository/src/test/java/com/external/helpers/MockedWebsocketClient.java

Added tests for SearchRequest parsing and Server response

Added unit tests for mock repository

---

Frontend/src/app/json-form/json-form-component.ts
Frontend/src/app/shared/form.data.service.ts

Try to fill search form
Click on Search Response
Click on Search
Form fields will not reset

Fix search form reset

---

Backend/microservices/data/src/main/java/com/ms/data/service/CloudStorageService.java

Added read XML feature to validate uploaded file

Schema validation

---

Backend/custom-starter/src/main/java/com/customstarter/model/schema/input/SelectOption.java
Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/RaceCodeSelectBuilder.java
Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/SexCodeSelectBuilder.java
Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/StateSelectBuilder.java

To test need to rebuild starter

Rename "Unknown" to "Select..." in selects

---

Frontend/src/app/admin-view-schema/admin-view-schema-component.ts

Format JSON in schema viewer
